variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.3"
  ANDROID_SDK_TOOLS: "26.1.1"
  ANDROID_SDK_VERSION: "6200805_latest"
  ANDROID_NDK_VERSION: "r16b"
  
stages:
  - release
  - test

containerize:
  image: docker:stable
  stage: release
  tags:
    - aws
    - m4-large
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  script:
    - docker login -u="$DOCKER_REGISTRY_USERNAME" --password="$DOCKER_REGISTRY_PASSWORD" $WISTRON_DOCKER_REGISTRY
    - docker build
        --build-arg ANDROID_COMPILE_SDK=${ANDROID_COMPILE_SDK}
        --build-arg ANDROID_BUILD_TOOLS=${ANDROID_BUILD_TOOLS}
        --build-arg ANDROID_SDK_TOOLS=${ANDROID_SDK_TOOLS}
        --build-arg ANDROID_SDK_VERSION=${ANDROID_SDK_VERSION}
        --build-arg ANDROID_NDK_VERSION=${ANDROID_NDK_VERSION}
        -t ${CI_REGISTRY_IMAGE}:${ANDROID_BUILD_TOOLS} .
    - docker push ${CI_REGISTRY_IMAGE}:${ANDROID_BUILD_TOOLS}

test:
  image: docker:stable
  stage: test
  allow_failure: true
  services:
    - docker:stable-dind
  tags:
    - aws
    - m4-large
  script:
    - docker login -u="$DOCKER_REGISTRY_USERNAME" --password="$DOCKER_REGISTRY_PASSWORD" $WISTRON_DOCKER_REGISTRY
    - docker pull ${CI_REGISTRY_IMAGE}:${ANDROID_BUILD_TOOLS}
    - docker run ${CI_REGISTRY_IMAGE}:${ANDROID_BUILD_TOOLS} sh -c 'curl -LO https://codeload.github.com/android/views-widgets-samples/zip/master && unzip master  && cd views-widgets-samples-master/CardViewKotlin/ && ./gradlew assembleDebug'
